### PR TITLE
Add ability to move downloaded files to any external directory

### PR DESCRIPTION
**Pull request by kabukky**
Changes:
- Added a new Activity to choose directories that will be used to move downloaded files to (user needs to use the system folder picker to give the app access to the external directory)
- Included [guessit](https://github.com/guessit-io/guessit) via https://github.com/kabukky/guessit
- Watching the history file for changes
- Using the NZBGet API to get download info and set a handled flag to ignore downloads after they are moved
- Moving finished downloads from destDir to the user defined target directory

This is mostly tailored to my needs.
I guess we could also recreate VideoSort functionality since we now have guessit in Java.
For some reason, at least in my tests, guessit seems to categorize every download that isn't a TV show as "movie", even if it is an ebook etc. Is that expected? How does VideoSort solve this?

### CODE REVIEW

**Comment by hugbug** [comment]
Thank you very much. Excellent work!

Can we get rid of Guessit? :-)

Using Guessit in the app only to determine video type seems to be an overkill to me. At the same time it adds a huge dependency and I prefer to keep them as low as possible.

Category information is often provided by indexers. For example if nzbs are fetched via RSS they can be properly categories (match with nzbget categories).

How about that: in the app show all categories (read from nzbget config) and allow user to choose destination directory (for each category)? That would be consistent with nzbget settings and doesn't require maintenance to cope with Guessit guessing failures.

> guessit seems to categorize every download that isn't a TV show as "movie", even if it is an ebook etc. Is that expected? How does VideoSort solve this?

Guessit is for video files only (at least it was the last time I checked). Sometimes it doesn't guess TV/movie-type correctly and there is quite a bit of hacking in VideoSort to cope with this. One more reason to not go that road in the app.

Thanks again for your contribution.

**Comment by kabukky** [comment]
Allright.
I would've preferred to automatically detect the type of download - but since guessit isn't reliable anyway, I'll settle with assigning a category to the nzb before starting the download.
I've updated this PR with the required changes to go the categories route.
Please try :)

**Comment by kabukky** [comment]
BTW: Feel free to change the wording in the StorageActivity layout. I just wrote down what came to my mind there.

**Comment by kabukky** [comment]
Adresses #11

**Comment by hugbug** [comment]
Thank you!

**Pull request merged**
