### PR TITLE
Added: Long Running Foreground Service, Android TV Support, Auto Start Daemon On Boot

### PR DESCRIPTION
**Pull request by kabukky**
Gradle was updated by my Android Studio (3.2.1).
Maybe because of the .gitignore, some meta files are also in this commit.
I guess you could cherry pick if you'd like to stay with the older Gradle version.

### CODE REVIEW

**Comment by kabukky** [comment]
Addresses #4, #6, #8

**Comment by hugbug** [comment]
Thank you very much!

Do all the changes preserve compatibility with Android 5-8 (versions supported by current app)?

**Comment by kabukky** [comment]
Yes, since I haven't touched the targetSdk and I am not using any non-SDK functionality, Android version compatibility stays the same.
I tested the changes on my S7 (Android 8) and Shield TV (Android 8).

**Comment by hugbug** [comment]
**Great work you've done!** I'm about to merge the PR.

Works like a charm on my Android 7 tablet.

I have one small issue with the project files. In your commits the file NZBGet.iml was renamed to android.iml. I've updated Android Studio and Gradle and when I open the project the studio renames android.iml back to NZBGet.iml. If I commit the changes would your Studio rename the file again to "android.iml"?

I'd like to somehow to achieve a project state where we both can work on the project without changing build config files every time. I've created a test branch (which includes your PR) where the changes from my IDE are committed - branch [test9](https://github.com/nzbget/android/tree/test9). Can you please pull that branch and test if you can compile it and the IDE doesn't change any files?

**Comment by kabukky** [comment]
Thanks!

I've tried the test9 branch, but editor files are still being changed/added:

.idea/misc.xml
.idea/modules.xml
android.iml
app/app.iml

This is probably because I cloned the repo into a folder called `android`, not `NZBGet` as you probably have. Android Studio seems to use the folder name as project name.

I could just rename my folder, but some changes in the `.idea` folder will probably be commited anyway.

The cleaner solution is probably to add *.iml and .idea to the gitignore and delete the old files form git.
See:
https://stackoverflow.com/questions/16736856/what-should-be-in-my-gitignore-for-an-android-studio-project
https://gist.github.com/iainconnor/8605514
etc.

**Comment by hugbug** [comment]
>This is probably because I cloned the repo into a folder called android, not NZBGet as you probably have. Android Studio seems to use the folder name as project name.

Indeed, the folder is called NZBGet on my PC.

---

Removing unnecessary files from source control is always a good idea. I didn't know the folder ".idea" and ".iml"-files are not required and can be recreated by IDE when necessary.

I'll test this and update .gitignore when I'm back at home later today.

In the meantime maybe you could do a test too:
- close IDE;
- delete folder .idea and .iml-files;
- start IDE, open the project and try compiling.

Does it work, were the necessary files recreated without issues?

**Comment by kabukky** [comment]
> In the meantime maybe you could do a test too:
> 
>     * close IDE;
> 
>     * delete folder .idea and .iml-files;
> 
>     * start IDE, open the project and try compiling.
> 
> 
> Does it work, were the necessary files recreated without issues?

I tried that and it all works fine still. I could build the APK and the files were re-created by Android Studio

**Pull request merged**
